name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ?? Checkout repository
        uses: actions/checkout@v4

      - name: ?? Setup Node.js and PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 10.19.0

      - name: ?? Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: 'pnpm'

      - name: ?? Install dependencies (frozen lockfile)
        run: pnpm install --frozen-lockfile

      - name: ?? Run Prettier (safe mode)
        run: pnpm prettier . --write --ignore-unknown || true

      - name: ?? Run all checks (types, lint, format, build)
        run: pnpm run check:all
